apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: b4ygnkvwg-python
  janus-idp.io/tekton: b4ygnkvwg-python
  backstage.io/kubernetes-id: b4ygnkvwg-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b4ygnkvwg-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
